{"stats": {"errors": 1, "failures": 0, "passes": 1, "skipped": 0, "encoding": "UTF-8", "total": 2}, "results": [{"classname": "index_test:FieldElementTest", "name": "test_add", "time": 0.00034809112548828125, "type": "success"}, {"classname": "index_test:FieldElementTest", "name": "test_sub", "time": 0.000316619873046875, "type": "error", "errtype": "builtins.RuntimeError", "message": "Num -15 not in field range 0 to 30", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pb-tester-ccdle12/ecc-add-sub-jsong-pb-sf-072618/test/index_test.py\", line 20, in test_sub\n    self.assertEqual(a-b, FieldElement(16, 31))\n  File \"/home/pb-tester-ccdle12/ecc-add-sub-jsong-pb-sf-072618/index.ipynb\", line 63, in __sub__\n    \"### Test Driven Exercise\\n\",\n  File \"/home/pb-tester-ccdle12/ecc-add-sub-jsong-pb-sf-072618/ecc.py\", line 12, in __init__\n    raise RuntimeError(error)\nRuntimeError: Num -15 not in field range 0 to 30\n"}]}